name=input("What is your name ")
print(f"hello {name} today you will help me tell a story")
print("")
print("")
location=input("now pick a location ")
print(f"{location} is a amazing choice")
print("")
print("")
weather=input(f"now pick the weather for {location} ending in y ")     
print("")
print("")
animal=input("now pick an animal ")
print("")
print("")
animal2=input("pick one more animal ")
print("")
print("")
name2=input("give me a random name ")
print("")
print("")
emotion=input("next pick a emotion ending in ly ")
print("")
print("")
activity=input("next pick an activity that the animal would do in city ")
print("")
print("")
adjective=input("lastly I want you to tell me a adjective ")
input("")
print("lets tell our story so far")
input("")
print(f"one day in {weather} {location} the {adjective} {animal} named {name} and") 
print(f"the {animal2} named {name2}wandered around the city and went to {activity}")
print(f"they both ended their lives {emotion}")
input("")
print("thanks for helping me tell a story")