name=input("What is your name ")
print(f"hello {name} today you will help me tell a story")
print("")
print("")
location=input("now pick a location - ")
print(f"{location} is a amazing choice")
print("")
print("")
weather=input(f"now pick the wether for {location}") 
print("")
print("")

print("lets tell our story so far")
print(f"")