name=input("What is your name ")
print(f"hello {name} today you will help me tell a story")
print("")
print("")
location=input("now pick a location - ")
print(f"{location} is a amazing choice")
print("")
print("")
weather=input(f"now pick the weather for {location} ending in y ")     
print("")
print("")
animal=input("now pick an animal ")
print("")
print("")
adjective=input("lastly I want you to tell me a adjective ")
print("")
print("")
print("lets tell our story so far")
print("")
print("---------------------------------------------------------------------------------------")
print("")
print(f"one day in {weather} {location} the {adjective} {animal} wandered around the city")
print("")
print("")
print("thanks for helping me tell a story")